"use client";

import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";
import { Inter } from "next/font/google";
import React, { FC, ReactNode, useEffect, useRef } from "react";
import { DivContentSC, DivWrapperSC } from "./styles.page";
import Header from "./components/header";
import { IRefObj } from "./interfaces/interfaces";
import Footer from "./components/footer";
import HeaderForPage from "@/app/components/header/HeaderForPage";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{ children: ReactNode }> = (props) => {
  const { children } = props;
  return (
    <html lang="en">
      <title>Earthy</title>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <DivWrapperSC>
            <HeaderForPage/>
            {children}
            <Footer />
          </DivWrapperSC>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
