"use client";

import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";
import { Inter } from "next/font/google";
import React, { FC, ReactNode } from "react";
import { DivContentSC, DivWrapperSC } from "./styles.page";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<{ children: ReactNode }> = (props) => {
  const { children } = props;

  return (
    <html lang="en">
      <body className={inter.className}>
        <DivWrapperSC>
          <Header />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          <Footer />
        </DivWrapperSC>
      </body>
    </html>
  );
};

export default RootLayout;
